name: llvm-yu CI 

on: [push, pull_request]

jobs:
  build_and_publish:
    runs-on: self-hosted 
    steps: 
      - uses: actions/checkout@v3
      - name: Build and push the built image
        run : |
          docker login --username akaushikyu --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/akaushikyu/llvm-project:latest
          docker push ghcr.io/akaushikyu/llvm-project:latest
